#!/bin/bash
#===============================================================================
# mount-woodsden.sh — Mount WoodsDen Claude Docs share to Tower
#
# USAGE:
#   ./mount-woodsden.sh              # Mount the share
#   ./mount-woodsden.sh unmount      # Unmount the share
#   ./mount-woodsden.sh status       # Check mount status
#
# REQUIREMENTS:
#   - Run on Unraid host (not in Docker container)
#   - Credentials file at /root/.woodsden-creds
#   - WoodsDen share configured and accessible
#
# Generated by CC3 — 2025-12-24
#===============================================================================

set -e

# Configuration
WOODSDEN_IP="192.168.1.94"
SHARE_NAME="claude-docs"
MOUNT_POINT="/mnt/woodsden/claude-docs"
CREDS_FILE="/root/.woodsden-creds"
SYMLINK="/continuum/woodsden-docs"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

#-------------------------------------------------------------------------------
# Functions
#-------------------------------------------------------------------------------

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

check_credentials() {
    if [[ ! -f "$CREDS_FILE" ]]; then
        log_error "Credentials file not found: $CREDS_FILE"
        echo ""
        echo "Create it with:"
        echo "  cat > $CREDS_FILE << 'EOF'"
        echo "  username=YOUR_WINDOWS_USERNAME"
        echo "  password=YOUR_WINDOWS_PASSWORD"
        echo "  domain=WORKGROUP"
        echo "  EOF"
        echo "  chmod 600 $CREDS_FILE"
        exit 1
    fi

    # Check permissions
    local perms=$(stat -c "%a" "$CREDS_FILE" 2>/dev/null || stat -f "%Lp" "$CREDS_FILE" 2>/dev/null)
    if [[ "$perms" != "600" ]]; then
        log_warn "Credentials file should be chmod 600 (current: $perms)"
    fi
}

check_ip_configured() {
    if [[ "$WOODSDEN_IP" == "192.168.1.XXX" ]]; then
        log_error "WoodsDen IP not configured!"
        echo "Edit this script and set WOODSDEN_IP to the actual IP address."
        exit 1
    fi
}

check_network() {
    log_info "Testing network connectivity to $WOODSDEN_IP..."
    if ! ping -c 1 -W 2 "$WOODSDEN_IP" &>/dev/null; then
        log_error "Cannot reach $WOODSDEN_IP"
        echo "Check that WoodsDen is online and on the same network."
        exit 1
    fi
    log_info "Network OK"

    # Test SMB port
    if command -v nc &>/dev/null; then
        if ! nc -zw2 "$WOODSDEN_IP" 445 &>/dev/null; then
            log_warn "SMB port 445 not responding. Check Windows Firewall."
        fi
    fi
}

create_mount_point() {
    if [[ ! -d "$MOUNT_POINT" ]]; then
        log_info "Creating mount point: $MOUNT_POINT"
        mkdir -p "$MOUNT_POINT"
        chmod 755 "$(dirname "$MOUNT_POINT")"
    fi
}

do_mount() {
    check_root
    check_ip_configured
    check_credentials
    check_network
    create_mount_point

    # Check if already mounted
    if mountpoint -q "$MOUNT_POINT" 2>/dev/null; then
        log_info "Already mounted at $MOUNT_POINT"
        return 0
    fi

    log_info "Mounting //${WOODSDEN_IP}/${SHARE_NAME} to ${MOUNT_POINT}..."

    mount -t cifs "//${WOODSDEN_IP}/${SHARE_NAME}" "$MOUNT_POINT" \
        -o credentials="$CREDS_FILE",uid=99,gid=100,iocharset=utf8,vers=3.0,noperm

    if mountpoint -q "$MOUNT_POINT"; then
        log_info "Mount successful!"

        # Create symlink if it doesn't exist
        if [[ ! -L "$SYMLINK" ]]; then
            ln -s "$MOUNT_POINT" "$SYMLINK"
            log_info "Created symlink: $SYMLINK -> $MOUNT_POINT"
        fi

        # Test access
        log_info "Testing read access..."
        ls "$MOUNT_POINT" &>/dev/null && log_info "Read access OK"

        echo ""
        log_info "WoodsDen share is now accessible at:"
        echo "  - $MOUNT_POINT"
        echo "  - $SYMLINK"
    else
        log_error "Mount failed!"
        exit 1
    fi
}

do_unmount() {
    check_root

    if ! mountpoint -q "$MOUNT_POINT" 2>/dev/null; then
        log_info "Not mounted"
        return 0
    fi

    log_info "Unmounting $MOUNT_POINT..."
    umount "$MOUNT_POINT"

    if ! mountpoint -q "$MOUNT_POINT"; then
        log_info "Unmount successful"
    else
        log_error "Unmount failed"
        exit 1
    fi
}

do_status() {
    echo "=== WoodsDen Mount Status ==="
    echo ""

    if [[ "$WOODSDEN_IP" == "192.168.1.XXX" ]]; then
        echo "IP:        NOT CONFIGURED"
    else
        echo "IP:        $WOODSDEN_IP"
    fi

    echo "Share:     $SHARE_NAME"
    echo "Mount:     $MOUNT_POINT"
    echo "Symlink:   $SYMLINK"
    echo ""

    if mountpoint -q "$MOUNT_POINT" 2>/dev/null; then
        echo -e "Status:    ${GREEN}MOUNTED${NC}"
        echo ""
        echo "Contents:"
        ls -la "$MOUNT_POINT" 2>/dev/null | head -10
    else
        echo -e "Status:    ${YELLOW}NOT MOUNTED${NC}"
    fi

    echo ""
    if [[ -f "$CREDS_FILE" ]]; then
        echo -e "Creds:     ${GREEN}Found${NC} ($CREDS_FILE)"
    else
        echo -e "Creds:     ${RED}Missing${NC} ($CREDS_FILE)"
    fi
}

#-------------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------------

case "${1:-mount}" in
    mount)
        do_mount
        ;;
    unmount|umount)
        do_unmount
        ;;
    status)
        do_status
        ;;
    *)
        echo "Usage: $0 {mount|unmount|status}"
        exit 1
        ;;
esac
