#!/bin/bash
#===============================================================================
# check-woodsden-mount.sh — Health check and auto-reconnect for WoodsDen mount
#
# USAGE:
#   ./check-woodsden-mount.sh           # Check and reconnect if needed
#   ./check-woodsden-mount.sh --quiet   # Silent mode (for cron)
#   ./check-woodsden-mount.sh --force   # Force remount even if mounted
#
# CRON EXAMPLE (check every 5 minutes):
#   */5 * * * * /continuum/scripts/check-woodsden-mount.sh --quiet
#
# Generated by CC3 — 2025-12-24
#===============================================================================

# Configuration — must match mount-woodsden.sh
WOODSDEN_IP="192.168.1.94"
SHARE_NAME="claude-docs"
MOUNT_POINT="/mnt/woodsden/claude-docs"
CREDS_FILE="/root/.woodsden-creds"
LOG_FILE="/var/log/woodsden-mount.log"

# Options
QUIET=false
FORCE=false

# Parse arguments
for arg in "$@"; do
    case $arg in
        --quiet|-q)
            QUIET=true
            ;;
        --force|-f)
            FORCE=true
            ;;
    esac
done

#-------------------------------------------------------------------------------
# Functions
#-------------------------------------------------------------------------------

log() {
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    local message="[$timestamp] $1"

    if [[ "$QUIET" != "true" ]]; then
        echo "$message"
    fi

    # Also log to file
    echo "$message" >> "$LOG_FILE" 2>/dev/null || true
}

is_mounted() {
    mountpoint -q "$MOUNT_POINT" 2>/dev/null
}

is_accessible() {
    # Try to list the mount point contents
    timeout 5 ls "$MOUNT_POINT" &>/dev/null
}

is_host_reachable() {
    ping -c 1 -W 2 "$WOODSDEN_IP" &>/dev/null
}

do_mount() {
    if [[ ! -f "$CREDS_FILE" ]]; then
        log "ERROR: Credentials file missing: $CREDS_FILE"
        return 1
    fi

    mkdir -p "$MOUNT_POINT" 2>/dev/null

    mount -t cifs "//${WOODSDEN_IP}/${SHARE_NAME}" "$MOUNT_POINT" \
        -o credentials="$CREDS_FILE",uid=99,gid=100,iocharset=utf8,vers=3.0,noperm 2>&1

    return $?
}

do_unmount() {
    umount -l "$MOUNT_POINT" 2>/dev/null || umount -f "$MOUNT_POINT" 2>/dev/null
}

#-------------------------------------------------------------------------------
# Main Health Check
#-------------------------------------------------------------------------------

# Check if IP is configured
if [[ "$WOODSDEN_IP" == "192.168.1.XXX" ]]; then
    log "ERROR: WoodsDen IP not configured in script"
    exit 1
fi

# Check if host is reachable
if ! is_host_reachable; then
    log "WARN: WoodsDen ($WOODSDEN_IP) not reachable - host may be offline"
    exit 0  # Not an error - host might just be off
fi

# Force remount if requested
if [[ "$FORCE" == "true" ]]; then
    log "Force remount requested"
    if is_mounted; then
        log "Unmounting existing mount..."
        do_unmount
        sleep 2
    fi
fi

# Check mount status
if is_mounted; then
    # Mounted - but is it accessible?
    if is_accessible; then
        log "OK: WoodsDen mount healthy"
        exit 0
    else
        log "WARN: Mount exists but not accessible - attempting remount"
        do_unmount
        sleep 2
    fi
fi

# Not mounted or was stale - attempt mount
log "Mounting WoodsDen share..."
if do_mount; then
    if is_mounted && is_accessible; then
        log "OK: Mount successful"
        exit 0
    else
        log "ERROR: Mount command succeeded but mount not accessible"
        exit 1
    fi
else
    log "ERROR: Mount failed"
    exit 1
fi
